[project]
name = "mlsys-phase2"
version = "0.1.0"
requires-python = "==3.10.12"
dependencies = [
    "torch==2.3.0",
    "mcp[cli]",
    "openai",
]

[project.scripts]
mlsys-mcp = "mlsys_phase2.mcp_server:main"
mlsys-agent = "mlsys_phase2.agent:main"

[[tool.uv.index]]
name = "volces"
url = "https://mirrors.volces.com/pypi/simple/"
